# Generated by Django 5.0.6 on 2024-05-27 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='submission',
            new_name='CodeSubmission',
        ),
    ]
