# Generated by Django 5.0.6 on 2024-05-27 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0002_rename_submission_codesubmission'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CodeSubmission',
            new_name='submission',
        ),
    ]
