# Generated by Django 5.0.6 on 2024-06-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_testcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='sample_input',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='sample_output',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
